### PR TITLE
Add a sticky nav (+ misc nav improvements)

### PR DESCRIPTION
**Pull request by TJScalzo**
I "solved" the sub-pixel rendering issue by making the text in the nav bar bolder. Other than that, I made the positioning and size of the external links bar more consistent. I did the same with the ENFORCERS logo thing. 

I _would_ merge this on my own, except I think it'd be a good idea to get feedback from the people who know more than me.

(#98)

### CODE REVIEW

**Comment by TJScalzo** [comment]
I could be mistaken, but these changes could also address problems brought up in #93?
Maybe?
I'm too tired to look through it all right now...

**Comment by gluxon** [comment]
This looks awesome from a quick look through. Give me until later tonight for the full review. 🙂

**Comment by TJScalzo** [comment]
Thank you very much Brandon! I'm happy you took the time to look my work over. I'll definitely look into CSS locks, they seem very useful.

**Comment by TJScalzo** [comment]
I'm going to say that these changes close issues #93 and #98. If anyone has objections feel free to reopen the issues.

**Pull request merged**
